<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>M05 - Edit Sosial Media</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>723f7c40-a164-4190-8f6a-2fc63d8a8573</testSuiteGuid>
   <testCaseLink>
      <guid>fdcf72d8-0441-43ce-bd48-c3cc2e08444d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-LS-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b7e56300-9c16-4ce7-803b-cd0c073060ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMS-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>271344a3-2328-47ba-9942-4c1eb9fcf6db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36f89a81-d641-40da-acf9-f14a4afcb705</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5e38ac1-3b3b-4101-9678-bbaa8656e376</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13664bb4-a481-4328-9723-6a90805b5d8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3f6697d-f11a-4bda-a574-53d55a73e441</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>067b628b-741f-483e-8038-add0b598d942</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d928c6b-1ab9-4b9e-a75a-157018f77ee3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b38e6f6-3c20-48cf-9a3b-b0cda1e75854</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>350f0644-997f-4e6f-bb4f-474f2e2f7708</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMS-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>281c2c8a-affd-43cc-a364-dc1a666e2a8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29509ef8-3d94-4496-b242-4fd19269dc30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5c1cca31-86be-4cbc-8628-aefad5527589</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMS-003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e138584-1de9-470c-9b05-adefcf7169c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b41288d-521b-47a6-9a3c-01454082fd3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMS-004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e07dcd5-5a94-4758-8f0d-dff04a2a81ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc2f4c4b-0ad7-4c7c-aa58-fe5cfe386495</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f9e0d48-ff29-4b07-b04e-e06155e91d7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ed4d528-65d8-47d6-abc7-167a285beea3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55a08f3f-1dd7-48f1-8fcb-edd74ac17e6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72997d70-c5e4-450d-b43f-98e8c6ad5514</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eb0270c-7238-428d-a345-69d7b18f1786</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b17cb0e-7168-4cb6-9a69-1fe95126dc26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91a55a90-cd01-4e60-98e3-7b5bbefd522a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMS-005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f7b0c04-f4d6-4d7b-bcc6-5c4409eccad8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccbefa58-2137-42ee-96ee-d32b6158dbd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56c392ee-43e0-41ce-a1e5-eb870660102f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d2c8ad0-899f-43b6-9a94-980ac1144d4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3839a2a8-10b2-4ec0-9312-9d9a1e5d0af0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04db2c97-4935-400b-a865-3c1803fb5b71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f2a4ada-35ca-4810-8cd5-b99bdb39d000</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>279ca3a4-f330-4a3c-83a1-0e84f45219c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>096fe730-90ad-42d8-a203-c1ca17b74308</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMD-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ff18d81-ea5e-4256-9883-c22b78e559cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>107c123a-d8ee-48bf-8b2e-8764938fa352</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e3178de-5c46-4998-af42-55551522b929</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c71c9cdc-c54b-4689-a3da-cfc31a9a3370</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7299f7dc-3696-45d4-900f-6747ceefddb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5919b70c-18d6-4734-8311-e19fa20f9fdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8a2dfde-5c25-4830-871f-1d54d3f0f350</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f376af7-8fd1-4d14-9a76-383ecc804043</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8c7cfbc-edf4-47a1-b328-e080ab831d1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc55baf9-388e-4fcf-aeee-db6b1470189b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9050a8a2-976c-48f8-af4d-34e536232d07</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12da92ae-64d5-4a27-9360-f1b1b046ae36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f96c27e4-f72b-490e-88e5-5f7c0befad72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f91a8e9f-7fb5-43e9-a19b-788284d95566</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9be7af05-fc88-438b-b5b8-2d4e4708edcc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55fa6f4e-32d4-40a5-b87f-24b92694e771</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>819345b2-a391-4da9-9783-e0f7dbeb065c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83b9bd6b-b918-4d3a-abf6-7c9e1c54325e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56bc45e6-2cbb-4d6f-82d3-30d5f137f862</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-006</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ba09669-80ef-4b47-90d8-e6183b7f19ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61e56858-becc-4431-a8f9-86dd06d65a1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-007</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86554917-b591-4ae1-9651-b890bb41f8c3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1a580d3-1e55-45be-bad5-07a7168df4c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-008</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29a3c0f2-4d8c-478b-8f3b-786f6dd35693</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5057c0e-f634-46be-b870-5802ebcee836</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c12ebe3-f467-4aa8-ae52-fe9f2a75a80f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c10540c1-0095-40d8-8e9a-0de11e23a747</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c2963b3-4014-421f-b339-e9a9af6dbcc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85afb4e6-1c92-4645-b6f7-4660cede812e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c37dfafa-c02d-457b-964b-ea5dc1641713</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90c0e18d-78c7-4f34-a97f-470e8882e2e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65cdc75d-5c08-460f-be62-53e16074578b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-009</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbb9f809-f58f-4a8d-9ebf-10b1331558aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b538d26f-70b3-41ff-b4ce-b886f5d65d0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6ba8a94-0708-4c8d-a57a-36a4e7ade472</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2636eab3-514c-4def-9f82-86f046d09f97</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79895142-1208-4343-8e0a-28774b2900ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d1a238-90cc-43a6-b104-511b6512916d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0daaa772-937b-4158-ae44-706ca3bc0dae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36285362-d37b-4e11-98a6-bea1367aa3ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5374529b-c0c3-4fbf-8233-5fba5dc29d22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-010</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2473fe10-e4fc-40de-bf9d-123c4531bc74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>736343a9-45ac-40d8-ba99-8b92c79f2f8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-011</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6965e399-bf76-49a8-9ec5-962e7a86092e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>babe2721-d8f3-49de-b6e7-835bab629483</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-012</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce3ef8a0-63cb-4aae-92ed-02b57babb8df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb84c38c-7b3f-4d64-8c8e-ca10641cd633</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/M05 -Edit Sosial Media/TC-ESMF-013</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fe71bbb-a751-4dcc-8244-30dc4bbcce23</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
