<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>test untuk test case konfirmasi pendaftaran</description>
   <name>T08 - Konfirmasi Pesanan</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c71d4f66-37d6-40c3-a46b-8bc506549b58</testSuiteGuid>
   <testCaseLink>
      <guid>310f8050-0d6b-4336-aff6-e80f72f0c570</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-LS-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>08c5f417-1095-45bc-a357-34045cefe296</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-OS-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ebdbd4f-d211-4275-990f-ca3749feb3a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb625aa5-6e13-4063-8b02-de65f51f5e52</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ddb7a17a-e6f5-4826-99cb-3882447e4c5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-OS-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e74f7414-5286-4dc9-b19f-08ee4b1fc0c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72b16969-0ed4-4f17-a133-e38ec3a5fca7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>872ffc3f-a10e-494d-b681-107e23806e71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KS-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70148cbb-b72d-4045-b118-931ee2113cc7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b7535fb-2a75-48fd-982c-ad9a3bfd2e4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KS-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4a66d97-fbe7-4b02-b0a5-b07deaf3417b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d4c4e3b-7b04-408a-aa08-d00b3f6c2d65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KS-003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa9e58b3-6fdf-4ee3-907b-64ad88c9c0e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>910fbbd0-1c4f-478d-81ab-c7e67f64730b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8116355e-813d-4388-9f92-76e78e8818df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KS-004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af0d35a6-e79e-4ce7-bbcb-1ae952b77db7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29cc2171-cc99-4529-9ae8-6333bf2dfc77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baf09919-935e-4f81-9d07-ab32500c3f22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>065bc2d4-7531-47e1-a30e-17a21d1ca8d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KS-005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f1c7cab-e468-4967-b268-1605b81fc455</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03fdc388-dbc2-4f15-9d52-46b09feaaf03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KD-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51852059-04bb-4799-8c5a-c5159db6a2f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0d91f586-4a41-4fab-b729-f20d4326eaf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-AK-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6524f5eb-fc65-4b25-9357-fd909a89229e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-AK-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bf3047fd-992a-46a9-8726-e96d21216740</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-AK-003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4a4352a3-3d8f-474b-a8fd-5e0db77934fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-AK-004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>648e9741-bbd8-4055-bc4c-d2ccf60dec18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a3e1026-5016-43fd-aeb8-d5a8bb4b1f3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-AK-005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b56e5c41-081b-4d5e-82c5-2eb3218a70f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b67c1c5-0665-4380-a441-14f1750b7223</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d62c0d3-aa65-489e-9079-9094c40d218f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab000dff-e038-47af-8bb5-8cc02007eac9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d450cc9-2c08-4e79-9696-6fea13d96cdf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f50eb7c0-bd0d-4eed-8daa-cb7114569f87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83b5228e-4054-4825-b09b-5d542a5a477a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d1ad382-8a17-45b3-8c7b-d6c949006116</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>314f93cc-7cdf-483a-bb4e-d2237a4e79ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>abf10474-f375-4efc-8f2f-20d10a3e9f98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b689d15d-737d-490f-9242-3fc3c72bc373</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6820ff4-40ac-4874-bf73-1ed6fa205cbf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78836bca-e907-4b5e-b3d6-af8caa10a72e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0ceaf23-7ed1-4280-a190-de1fea6ef0e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97db5238-948b-4abb-ae98-c8e0e14eae18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef0682a4-5153-48da-87f2-b281291d62a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-006</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70aa53b7-6f35-43aa-a817-82689c4a4980</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>352095a4-57ed-4e2b-8fa8-b16751977e9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d04bddf1-0a31-4806-b000-2d20caf44a1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>18b490d6-1a35-4196-8a26-b78fdebe32d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-007</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de521ff2-8777-4c34-8524-12eda8203d0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17acd3ed-a1fc-4017-b04c-bf9deb59f939</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7fe974d-468f-4d90-865e-951ae494d6b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>536e9dd9-bd3a-4a20-806b-122906c1c640</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-008</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b6be35b-5baf-424c-9676-4da61db07928</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ddf795e-2b4f-4d31-acd5-c270dc952ecb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3f95b0c-3f17-48be-87fa-a66892953590</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59d63f58-a8bb-4c16-843f-fa31f7bc8ee4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-009</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01f57d7d-d118-4e6a-9f7f-255f718728b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a308b26f-04f9-4fab-b797-83a9aff56cec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63ce90f5-cac0-49f1-9506-5b654166e46d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-010</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b81eb39b-1e4a-41ab-91c0-05add4127341</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b2a1f75-5cfa-406d-9c2c-d00fb062a3db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45026fd9-c768-4338-af92-c7665e71c9d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-011</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49be27e8-777b-428c-98d6-e05fd823ca2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21b01ef2-b299-48e1-8d40-057f25e06793</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>efacc344-1bcb-4de0-892f-4dbe98a8e0c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-012</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cb690c1-a737-46a2-8a0e-9c7d3b676ee2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6288916f-3dca-4b21-8040-4ec89a8aa67e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9459054f-6ac6-47a9-816a-b7a945b87d65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-013</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>410c5796-e30e-4e7a-a5d2-d5dbb5baec8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef34bd13-ffcf-4e55-b2e6-266408e2dca5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73c0a19e-e0d5-4be4-9508-ff2d74d866d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>837d6332-f8ce-42d0-8877-24136d0ef4c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-014</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29a9c3db-510b-41df-8351-3e196e9c3cff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb516b3c-adc6-4fd7-baa9-22d9938ab3e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13503e07-1ebc-474a-bb1b-e642b8c54c4c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb5d8ad7-4997-4cb8-8977-8e7cad31591f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Konfirmasi Pesanan/TC-KF-015</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60433f2f-b086-4252-a0c1-6ffdee2042b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a6fa0f7-708c-493d-b32b-20fce9515b49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>346758db-e22a-4880-b561-62d732d48bbe</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
