<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>T08-Pendaftaran</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>22b5f6c4-dc54-4f5a-939d-3e1bf663ea5b</testSuiteGuid>
   <testCaseLink>
      <guid>3a13ca64-dc47-4245-b15f-7d6636fac317</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PS-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb799e4b-bc2e-4c25-8e35-87943cd3558c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>841bedaf-dd85-4698-a716-c8747a45aa94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92688489-dd18-4c29-9a15-0e9398031c15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d709e6cf-0d1c-49ec-8040-e7bebffd8c72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a4cb3e5-9113-447d-a0da-66de84c1b36c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PS-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>143d2603-02e1-4b21-a095-0df951c4dbd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d74dbd73-86ec-4820-820a-be8c3ec70b6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8536d4e-9df4-4563-a528-8173ee2856c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0858bcbf-b795-4303-90ee-fa6de3506492</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89e60b0f-ff7b-4553-8593-75f882965c3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PS-003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b60a04cb-4f26-48e3-a925-4895a36d863b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>845cd7c4-ce2f-40db-8a20-25af46ea11b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>849fe72b-f014-4b92-bd57-4814faa0750b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd845955-a659-45d8-97bd-1709af92274e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>65c14018-8388-4209-8db2-901e416e2ef4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PS-004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e4ff23b-87a5-4b46-9028-9166c0b793fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d280d50a-8fd2-4747-8da8-a0aa2c166537</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0eba687-d386-473e-a009-9dc17ec6159d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3d7c519-3a06-41b2-9bea-b43cab92b4a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e19dcb35-ab4d-49ac-84c9-7c616f5003af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PS-005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>843a50c0-cad1-46d5-856b-2cd6dff1607f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>322be63b-84ec-4fb6-b6ab-aeda9dfc6462</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7a49b89-02ca-43a3-8998-7b0989841617</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc900f3-3b04-42b4-bc24-414ec73076da</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f854826-8cfd-4439-bcae-e05c79267835</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PS-006</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee166206-83b7-4238-bab0-71a6b4f98329</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cde4eb0f-cd52-43c2-96f2-5810cf4b00c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f3e1d1f-46f7-43ce-a1c6-a92ec622471b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94c2e42d-4b3c-4576-9020-053b2b3cfb46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81934a0c-dbdc-484f-b12e-20ec41af9f2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PS-007</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f3df48b-5891-4312-8117-fc1a66bab95f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>619f06e1-c6da-4d2f-9f87-dc905185aa03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef3ea16d-9465-4be8-902b-0a2163711b1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7278c9f-1640-46d5-8015-b06f09fe55ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08fb0612-484c-4bc9-a2dd-b937d82b21f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PC-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04a97076-062f-4f12-8ac3-aa0a24ec443e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc23bad-33a4-42b5-a67c-f9a70f620f10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d29b649f-6678-430e-b8c9-b3ea47439932</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5d9cb93-d425-4e47-a355-c38d8e183b8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dda1e738-e844-45a2-bcc9-a0aea7c7f469</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PE-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>babf6395-7d61-4209-bcb2-15264c842262</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PE-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>beb406b8-7e87-48ff-b62c-542e70436f63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PE-003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5cc2a312-d18d-4b37-91e1-601ffb2b9545</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e94e6468-e0ff-4166-b127-c8fc98cbe7cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9aae207-ac65-408d-95ce-cad9056bb6b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89df7eb7-938b-481b-bb69-e7785354b490</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1597f989-2fe6-463a-a90d-1bd253f85ed3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5da11cb-0881-4ea2-8e1f-b3d20ec2086e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-002</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>383f8ba5-6e68-4635-9942-2e37df68b534</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5de67f75-ea33-40c0-92c6-c31c3d3f0fb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8697b829-c253-4ba8-9751-74a50928c4b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>696fbb26-689a-418e-ac79-a535f6ab846c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa7c0a8a-87d1-464d-a252-9144dd92665e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-003</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d51db4c4-8e1c-4834-830a-7dfe5a09ae96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a23a2cf5-c295-44de-ad02-1111ebc5dd08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2b26388-391b-46fc-aef1-3605349d7b0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b2df1a9-36ec-4515-a668-b6e865348cb0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12d31d9a-d2bc-42fa-b482-74578892bc6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-004</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caaf55b1-232d-4f48-8127-afc8db535a53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92c9a108-a27b-424c-8eb8-239628316822</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddb65068-cd55-4189-af07-88bfd91739d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae14f38c-218d-4ef3-8edf-417e18e665e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b451c40d-7c3a-4593-9ee6-c8705e5b2bc8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-005</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d5bbf9b-a95b-4024-908a-ae4c9766924b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>461d61f6-d62d-4a36-89fa-0f59ba9d6a49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe44da4-a7f4-4bd9-b083-2ec696cc0ea3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23e999e2-9189-4e42-b24f-dff7d04286d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1aa91e52-835e-4bb6-943d-30433e3f8b8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-006</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0144291d-a210-42e7-ac46-d5a9860277c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e73e3b77-1f70-488e-9d32-d81184e6e601</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b0de9d2-a148-4fad-b7bd-de7343b05642</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5396f1ef-edf0-4cbf-a2aa-fce753a7b19a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a99a709-baa3-47db-b7eb-ec66c9d38f37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-007</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11302158-0ab3-4114-b918-06be972fcaa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fb461df-b58c-4d3c-87e4-81026fc610b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a18d4312-e2e4-47e8-bd8b-bb764c7b10c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff1ffa7c-ecb4-475a-b1d3-dcecaf226895</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2078bc1d-6642-40de-a283-1451eaf70a21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-008</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>241b6a66-b5ae-4dbf-9665-02cb11a37d83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d714ab5-d4a8-4466-9ff8-cc615a3a5e11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e9e819a-2fda-44a3-9040-09ebd78657a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d885e80f-352e-49e3-9eac-5b4c1277df27</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b6bf18f-df09-43e0-ba13-ff5bb6b0cf9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-009</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6727f65-a12c-4ef8-91bc-6e5c388cc93d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdd3fe46-f79a-4f64-b7e9-b8ccdd55a0ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f12039ac-2ffb-4f46-aa2e-49c000c61f78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d9359d7-d8b4-4437-b17c-6f41824c69f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a9bb69fa-285e-4f11-87ae-e48bfa946a5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-010</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b086ddd-2b5f-4972-81a2-a180ae8a31db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0180a8f2-d636-48e8-8aa0-f5e265213c98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb963f87-f43f-4728-a8a3-e0d695ca109d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c700b721-da82-4d82-93eb-5e1ad99dba2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a22ae5e0-632c-4cdc-b536-d7d0d399d21d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-011</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ac96d8-a8bc-4da8-9c0f-c9e2618a33b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9afd45b-25cb-45af-831e-a36b3c0622f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f10d594-bdfd-49f6-8fca-cf55709605e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e9df7d4-c898-49b3-8d36-1b2199bbabbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c463f85e-0f15-436d-a89d-391581250781</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-012</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c823bb4-3d97-44f4-a2b4-10c18adedae2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf16b292-a6bb-4b9c-828f-ea1f10db37ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c389308c-8e6d-4d61-8013-8dd4f9336121</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7033ff8-fb8b-4eeb-8802-9095fdb75da1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3aa6d0fe-4494-4979-9562-0f9f5482eba0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-013</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d7430b7-9a8b-49f0-b3e6-8b9279fd44e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f64ce5dd-8f2c-48bc-8b27-2e2e269b4169</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e27504a-7657-4abd-bd95-4d523e5b8486</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebb4dc15-d969-4341-b075-2eac99fd44c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>419dd953-16c7-442a-8f39-8ac718bd9f9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PF-014</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>293313d4-8c5a-490a-bca8-88af5191df2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da2cce0c-5f6a-4d69-9138-c398f0830956</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abe21183-c029-4c0d-b8bb-df561c4c549b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bd4ff71-4fa3-40dd-a835-f0b57d9d27b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7fa4605-90fb-4a3f-96bf-c945b7f28d1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/T08 - Pendaftaran/TC-PDS-001</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0147e0d5-d3d3-49af-a882-ce23da16790c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7964fb75-332a-4cc5-a3f7-d6d9d400c3a9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
