<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Beli Sekarang</name>
   <tag></tag>
   <elementGuidId>e40e2bcc-2309-42e9-9b77-b33910ea2f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ps-product__shopping.d-none.d-sm-block > button[name=&quot;beli&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='beli'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>421f8299-8f24-4189-b2b6-17412ee57c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>90f23814-fe8d-454f-9fbe-57dfb7818015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>beli</value>
      <webElementGuid>642f6e06-df5a-473e-988e-7c0bf532d52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-btn</value>
      <webElementGuid>15a94c15-280a-4d4e-9f7d-10be30d9298a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1de2a3db-0048-4569-b585-17d74678519e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beli Sekarang</value>
      <webElementGuid>b0acf7af-a989-4ac9-bb7c-1c342c864ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;ps-page--product&quot;]/div[@class=&quot;ps-container&quot;]/div[@class=&quot;ps-page__container&quot;]/div[@class=&quot;ps-page__left&quot;]/div[@class=&quot;ps-product--detail ps-product--fullwidth&quot;]/form[1]/div[@class=&quot;ps-product__header&quot;]/div[@class=&quot;ps-product__info&quot;]/div[@class=&quot;ps-product__shopping d-none d-sm-block&quot;]/button[@class=&quot;ps-btn&quot;]</value>
      <webElementGuid>328db238-c9c3-402c-89fd-6b36a75f5507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='beli'])[2]</value>
      <webElementGuid>9f3ce982-0e50-4c87-89c3-99dca9466839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Keranjang'])[2]/following::button[1]</value>
      <webElementGuid>de6b69da-7421-47d0-8f33-c271e3413ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::button[1]</value>
      <webElementGuid>9b3c9e34-b3de-4c39-b034-5f3438cfc040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporkan Penyalahgunaan'])[1]/preceding::button[1]</value>
      <webElementGuid>24d1d3ff-630a-400c-8cf2-d90389acff45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories :'])[1]/preceding::button[1]</value>
      <webElementGuid>608712a7-1bde-4b8e-9252-022dca127802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>b11e9b62-352b-4800-a9a0-2742d3ed99fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'beli' and @href = '#' and (text() = 'Beli Sekarang' or . = 'Beli Sekarang')]</value>
      <webElementGuid>ab7bd7a2-0406-459b-87d1-5407c384639f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
