<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ONGKIR</name>
   <tag></tag>
   <elementGuidId>f6e2a487-5ade-44c4-8590-7ad9728f6661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serv-99-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[1][@id='serv-99-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>805fd730-3e85-45ee-8862-3015be47bd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serv-99-2</value>
      <webElementGuid>94454cba-1f09-4d1c-af8d-b3edb70c1107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>klikongkir10('2','SOPIR','30000','30,000',this.id)</value>
      <webElementGuid>6547f626-8e63-43e4-8e2d-ac86762b6c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item clearall-kurir</value>
      <webElementGuid>9812df46-0139-41a0-bd66-33a323ca9603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vixion R (BA 4665 LN) Rp. 30,000 / JANGAN DIHAPUS!!!!!</value>
      <webElementGuid>ed4ba7af-5f2c-4536-ac28-31dc7c1f3867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_sopir_div1&quot;)/li[@id=&quot;serv-99-2&quot;]</value>
      <webElementGuid>6c3424d5-742a-4025-928f-473d561286a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='serv-99-2']</value>
      <webElementGuid>30527842-29a7-4c27-b1f9-28b6d21b81fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_sopir_div1']/li</value>
      <webElementGuid>c2b80633-233e-4263-a4f9-162c5f97fb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim via COD (Bayar Di tempat)'])[1]/following::li[1]</value>
      <webElementGuid>522fea88-406d-4fda-ba7e-4584e3442727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarii Sentral Java'])[2]/following::li[1]</value>
      <webElementGuid>de6f2a04-265d-4cc1-bb0e-aa605048b9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li</value>
      <webElementGuid>ca3fe3ca-b722-409f-b19e-d3224fafb677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'serv-99-2' and (text() = 'Vixion R (BA 4665 LN) Rp. 30,000 / JANGAN DIHAPUS!!!!!' or . = 'Vixion R (BA 4665 LN) Rp. 30,000 / JANGAN DIHAPUS!!!!!')]</value>
      <webElementGuid>1dfa41f8-5081-4cf5-9f44-675dc4bd289d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
