<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nama yang tf</name>
   <tag></tag>
   <elementGuidId>1f4054d2-b0bc-4f73-a9b6-fd71a01ff4e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example1']/tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c48f5534-6f12-4df6-81ee-64bf7ec57ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>runarun</value>
      <webElementGuid>c86a5e43-29f9-4c1b-b5a6-2f4ba3b5c07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[5]</value>
      <webElementGuid>8c024b40-ec22-4ee5-a87f-ffab33fcc383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[5]</value>
      <webElementGuid>9131feed-2cd0-41ad-8c58-1c2802d375f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRX91.20230913141442'])[1]/following::td[3]</value>
      <webElementGuid>94736631-f943-4dcd-9a37-b5824e77fa2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waktu Trx'])[1]/following::td[5]</value>
      <webElementGuid>d8b397b3-a6ba-4435-acfc-e398eb0a3536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank BNI Syariah'])[1]/preceding::td[1]</value>
      <webElementGuid>05b218ad-9ab4-4c19-8399-f76d043ae621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lunas'])[1]/preceding::td[3]</value>
      <webElementGuid>75bb6415-39df-40b1-9a50-2ed12b3508c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='runarun']/parent::*</value>
      <webElementGuid>db1bd1a0-d589-47d7-b926-7480b80f8afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>480783ec-b0f8-406b-aec1-f811cf60052a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'runarun' or . = 'runarun')]</value>
      <webElementGuid>6f85a615-d0d6-4aa7-85d4-ef19d4e229ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
