<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tf saldo akun</name>
   <tag></tag>
   <elementGuidId>c67f4a31-5ecf-4f0b-886c-c1b9d923fc51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='saldo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#saldo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f249d6fc-2ec2-470b-a1fd-c644fe84cc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2608673a-7d1b-4552-a9fc-cbc8a1218b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>metode</value>
      <webElementGuid>133c2b39-d36f-4a64-86ff-71ea25aaa151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saldo</value>
      <webElementGuid>a28a1598-9308-4246-8764-6771c271792d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>saldo</value>
      <webElementGuid>c45ca04a-edd4-4fc3-850b-f6b8c2e2c221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saldo&quot;)</value>
      <webElementGuid>08c3c3b8-dace-4808-a291-67a1dadae671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='saldo']</value>
      <webElementGuid>40ca02fa-b51e-4316-a16e-6f49ece3bdb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>946589dc-51b6-4a8d-9dab-4b26997c0886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'metode' and @id = 'saldo']</value>
      <webElementGuid>71a84e8b-954e-463e-aa48-03d94b4b058b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
