<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pembelian</name>
   <tag></tag>
   <elementGuidId>8dc30dbf-32b8-41d9-a911-a24062b9d7b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Pembelian')])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.ps-section__links.d-none.d-sm-block > li:nth-of-type(6) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bbae0491-b063-4c7f-be9b-2e0bce3a783e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/members/orders_report</value>
      <webElementGuid>30dcf814-0463-483f-b1a2-044c083c073f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pembelian</value>
      <webElementGuid>4090ea6e-1fa5-4224-8c43-7f11e8bf44fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;ps-vendor-dashboard pro&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ps-section__content&quot;]/ul[@class=&quot;ps-section__links d-none d-sm-block&quot;]/li[6]/a[1]</value>
      <webElementGuid>33b0f008-a9b0-4d64-b421-8bfb3ee008f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pembelian')])[3]</value>
      <webElementGuid>6bcb0fcd-32ec-42b3-b8e8-df74731ca7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[3]/following::a[1]</value>
      <webElementGuid>3171520b-d581-435d-8fda-87d230fed3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keuangan'])[3]/following::a[2]</value>
      <webElementGuid>a00cb690-b597-464a-b1c5-28a85dc88753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PPOB'])[3]/preceding::a[1]</value>
      <webElementGuid>b5743d6f-9bb1-4496-b14b-46d3f2945425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadi Kurir'])[1]/preceding::a[2]</value>
      <webElementGuid>2de84e93-d5a2-421f-8ca3-3512386d66a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://10.9.2.63/ecommerce/members/orders_report')])[5]</value>
      <webElementGuid>4678185f-5ac6-4815-bf65-f5a2a11b8174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/ul/li[6]/a</value>
      <webElementGuid>e65e50c3-11a9-431e-a090-d2315d3abf27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/members/orders_report' and (text() = ' Pembelian' or . = ' Pembelian')]</value>
      <webElementGuid>09f4a93b-ecc8-4ae3-a80e-43822214e437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
