<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>no invoice</name>
   <tag></tag>
   <elementGuidId>8dfa5497-7705-4fd1-9af7-84397fbb48c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pending']/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-10 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>304f3b55-e1ea-4d2a-88cd-cdc9ffad6dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/konfirmasi/tracking/TRX91.20230907100309</value>
      <webElementGuid>8d9db4ec-14e7-46a0-9286-9745d3776f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRX91.20230907100309</value>
      <webElementGuid>7377410f-d0e7-4ca0-9b45-4ae6380f1c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pending&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-10&quot;]/a[1]</value>
      <webElementGuid>dbbad9e4-7129-444c-b593-f633e1bac7e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pending']/div[2]/div/a</value>
      <webElementGuid>8998ae59-3429-477e-b502-327cc5d0011d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'TRX91.20230907100309')]</value>
      <webElementGuid>62cc48ab-0538-4a09-8f37-e0a96e2303e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice / Seller'])[1]/following::a[1]</value>
      <webElementGuid>6d1bafab-fe13-4fb4-ab78-b642286194cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalifah Umayyah'])[1]/preceding::a[1]</value>
      <webElementGuid>4e23bc09-5bbc-4606-8e13-dbd9f7cde126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::a[2]</value>
      <webElementGuid>276ea660-26ae-4484-953f-a7ac5b26efcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TRX91.20230907100309']/parent::*</value>
      <webElementGuid>ed3f033b-06a7-47d6-a015-c2325d76f287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://10.9.2.63/ecommerce/konfirmasi/tracking/TRX91.20230907100309')])[2]</value>
      <webElementGuid>5288e40f-4b77-4f17-8f60-3a4fbc879f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>5aeabd4d-2be9-414d-a90d-3fee111f54ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/konfirmasi/tracking/TRX91.20230907100309' and (text() = 'TRX91.20230907100309' or . = 'TRX91.20230907100309')]</value>
      <webElementGuid>69549210-5ac4-4551-8e3b-06597bfa89f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
