<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar</name>
   <tag></tag>
   <elementGuidId>b0ad6db7-cf12-42bc-b651-cd6a5e02c6e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[8]/div/div/div/div[3]/form/div/div[6]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1bf91247-7957-496f-b257-a89adce6ad81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#register</value>
      <webElementGuid>12e959c0-db13-4cbc-b4da-c54380853ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>73eb3d4d-069d-453a-8376-3374d9189134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;ps-my-account&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ps-form--account ps-tab-root&quot;]/ul[@class=&quot;ps-tab-list&quot;]/li[@class=&quot;active&quot;]/a[1]</value>
      <webElementGuid>bbe2f262-1090-4949-bcf9-d70020e69a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Daftar')])[3]</value>
      <webElementGuid>fe09e848-eefe-4410-a10f-005966300295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/following::a[1]</value>
      <webElementGuid>0deeee93-7f88-434b-9e4b-c363042b1fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='White'])[1]/following::a[2]</value>
      <webElementGuid>ddbdcc30-151f-4d29-b52f-b34c440f6cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silahkan Masuk ke Akunnya.'])[1]/preceding::a[1]</value>
      <webElementGuid>f38ff684-ea80-4ed9-b1c2-991c1c2e156c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[2]/preceding::a[1]</value>
      <webElementGuid>02a5647f-0749-4ceb-954f-90b4ed8bda21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>f1061ce8-98b5-4f1f-a17f-4948493015f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#register')]</value>
      <webElementGuid>35bdaccb-b525-4d37-a234-100051835526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/ul/li[2]/a</value>
      <webElementGuid>04851685-6edb-4a93-a1f6-b2f6537ee457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#register' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>72789105-c18d-4c96-83f5-e230d8dd8808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
