<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input konfirmasi password</name>
   <tag></tag>
   <elementGuidId>f8198428-bef9-47f3-b78c-b8723db26035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;repassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='repassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14416ed8-7c14-4514-80ec-72688a2f3941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-auth</value>
      <webElementGuid>5150f0cc-663f-4e84-a41b-4bf38dd61ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>f39ee5e0-5c6f-4670-95da-b06dc82e8bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>058c43ae-38c9-46bc-8128-f6c2a8250238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Konfirmasi Password</value>
      <webElementGuid>dd4dc517-94fd-4da3-bc5c-fda59406e665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>nospaces(this)</value>
      <webElementGuid>6af69b66-1ba9-4e93-ad58-44079a0d75b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register&quot;)/form[@class=&quot;auth&quot;]/div[@class=&quot;ps-form__content&quot;]/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/input[@class=&quot;form-control form-auth&quot;]</value>
      <webElementGuid>38606fd1-86ea-4580-9bd2-06b79d8472c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='repassword']</value>
      <webElementGuid>62a99141-f4ae-4218-b40d-9699424a1426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register']/form/div/div[5]/div/div/div[2]/input</value>
      <webElementGuid>75222f24-d8ad-4686-a9c1-fa6e1f8ce53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input</value>
      <webElementGuid>add01791-7870-4be3-b24e-fa12aa55b81a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'repassword' and @type = 'password' and @placeholder = 'Konfirmasi Password']</value>
      <webElementGuid>3b4a83c1-c067-4391-a8cb-5314680974a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
