<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilihan Pria</name>
   <tag></tag>
   <elementGuidId>8b51eb81-adad-4c86-97cd-e2d4a9559d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;jenis_kelamin&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='jenis_kelamin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37721879-f6f4-4fcf-b44f-5f1d1a27e956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis_kelamin</value>
      <webElementGuid>bae1820e-1468-4678-a30a-a06faa2228d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>65bcf8d8-ce48-4f56-8fb5-a29b318516ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Laki-laki</value>
      <webElementGuid>e74adff5-95de-4d93-9394-4ca2b9d9aa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register&quot;)/form[@class=&quot;auth&quot;]/div[@class=&quot;ps-form__content&quot;]/div[@class=&quot;form-group&quot;]/input[1]</value>
      <webElementGuid>baf3dca2-9b82-41d4-a254-2d7e95fbfec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='jenis_kelamin']</value>
      <webElementGuid>f203d4aa-be09-45ef-aca8-adfc09b8d4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register']/form/div/div[4]/input</value>
      <webElementGuid>5806eeda-20f4-41fa-ba8c-29707591a9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>ec94e8c3-6305-4e58-a9a6-80d96d48e3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'jenis_kelamin' and @type = 'radio']</value>
      <webElementGuid>cd30fce5-32ff-4d5f-add9-fe1eee2adfe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
