<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input saldo akun</name>
   <tag></tag>
   <elementGuidId>3ae0457b-53ac-4b5c-b094-dfc67fc09e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='saldo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#saldo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a3b2d30-0fe1-43b9-83c1-7ebe11335bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bd3ca99a-b6f7-4142-835b-1dfc88c2744f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>metode</value>
      <webElementGuid>1e9f50f0-9646-4bbe-bf7b-2dd112012e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saldo</value>
      <webElementGuid>0d0c96d2-eb85-4d14-a35f-6bdc2b0f49b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>saldo</value>
      <webElementGuid>612b3e6d-cc90-45ac-b968-aab0fd4a4585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saldo&quot;)</value>
      <webElementGuid>18a3f437-4920-4af7-bcce-013c6a5fbbd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='saldo']</value>
      <webElementGuid>93bfb4e1-2f43-4bd7-aa64-35f224e513de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>a34f5f33-9901-4be7-85f0-39109c6db25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'metode' and @id = 'saldo']</value>
      <webElementGuid>d994e7ce-6ddc-4640-a101-fc72dce474b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
