<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>klik harga ongkir</name>
   <tag></tag>
   <elementGuidId>50f2593f-541f-42cd-a351-62d25fdb8ea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'serv-99-1' and (text() = 'Mio Sporty (BA 3456 CD) Rp. 13,000 / ' or . = 'Mio Sporty (BA 3456 CD) Rp. 13,000 / ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serv-99-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;list_sopir_div1&quot;)/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c12b9da7-86e6-4b67-8638-015a88d8819e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serv-99-1</value>
      <webElementGuid>2616e0b6-b651-4d11-b41c-457432682a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>klikongkir10('1','SOPIR','13000','13,000',this.id)</value>
      <webElementGuid>7a7deae6-0cae-4b3e-8542-a74700be0779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item clearall-kurir</value>
      <webElementGuid>c47bcd26-86f6-4a45-aad9-b2b5824a24f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mio Sporty (BA 3456 CD) Rp. 13,000 / </value>
      <webElementGuid>0e18e129-c0db-4cfd-9936-f62c1e87a5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_sopir_div1&quot;)/li[@id=&quot;serv-99-1&quot;]</value>
      <webElementGuid>a5a9e68c-f338-464a-b55f-c54fbab3184c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='serv-99-1']</value>
      <webElementGuid>60e63f79-0bbe-4aaa-9b0b-c8abf5390b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_sopir_div1']/li</value>
      <webElementGuid>58593d90-3b93-4d26-8c1b-a35f5db6d56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim via COD (Bayar Di tempat)'])[1]/following::li[1]</value>
      <webElementGuid>7eb2579c-d18c-40db-9e83-c76d9ec30007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalifah Umayyah'])[2]/following::li[1]</value>
      <webElementGuid>01a06ef0-ff39-4d11-8303-df2dfcc3ca73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li</value>
      <webElementGuid>b748cb44-9e59-44ce-9e6e-c99065ea7fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'serv-99-1' and (text() = 'Mio Sporty (BA 3456 CD) Rp. 13,000 / ' or . = 'Mio Sporty (BA 3456 CD) Rp. 13,000 / ')]</value>
      <webElementGuid>72ccf7a4-f9d4-49f8-a39b-2da775841760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
