<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Kirim via Kurir Lokal -Roda 2Roda 4</name>
   <tag></tag>
   <elementGuidId>00aa97ee-d343-44ee-a7e0-4d4b974adeec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='list_sopir1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list_sopir1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eb84e3ee-f289-4ec1-88b4-d7ffc6efc142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini text-success</value>
      <webElementGuid>be314715-db76-435e-9307-1463f4f26a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode_sopir1</value>
      <webElementGuid>e8258233-6ee3-4763-b216-61f16b94bfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list_sopir1</value>
      <webElementGuid>47c0c2a0-fecb-4fc2-a446-01dc011cea26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                              - Kirim via Kurir Lokal -Roda 2Roda 4</value>
      <webElementGuid>23fe59a0-c6ec-4c91-8758-5de08162d327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_sopir1&quot;)</value>
      <webElementGuid>d8db0726-cd50-492e-aae2-be4f0cdac1df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='list_sopir1']</value>
      <webElementGuid>0da53a6d-33af-4578-9185-1efb598ffe0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim via COD (Bayar Di tempat)'])[1]/following::select[1]</value>
      <webElementGuid>1e71637b-f76e-4e65-a0a1-0fc27f072874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalifah Umayyah'])[2]/following::select[1]</value>
      <webElementGuid>dcab86d1-be49-4595-bb38-3ac897fb1eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COD Tidak Tersedia!'])[1]/preceding::select[2]</value>
      <webElementGuid>cd80e782-ef2e-4a1b-a328-082466e7ae97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 1,500'])[1]/preceding::select[2]</value>
      <webElementGuid>6ddfbaec-6f94-4814-ae10-e2db96d40fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div/select</value>
      <webElementGuid>1e520125-a197-46cc-8524-eeb6311f14e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kode_sopir1' and @id = 'list_sopir1' and (text() = '
                                              - Kirim via Kurir Lokal -Roda 2Roda 4' or . = '
                                              - Kirim via Kurir Lokal -Roda 2Roda 4')]</value>
      <webElementGuid>3d7e01ec-6a79-4ca0-91b5-a37e4d255b01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
