<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifikasi masuk halaman admin (1)</name>
   <tag></tag>
   <elementGuidId>d68e7810-0595-4525-8666-6993914c61ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.logo-lg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/preceding::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3ec93c6-6762-40ae-87e6-53c91f2ea095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-lg</value>
      <webElementGuid>73cd408d-e2f6-4c53-8aa4-d8934ddfc5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TAJALAPAK.COM</value>
      <webElementGuid>05acfca4-0db1-4b62-aaa4-8739bc1fc7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-black-light sidebar-mini  pace-done&quot;]/div[@class=&quot;wrapper&quot;]/header[@class=&quot;main-header&quot;]/a[@class=&quot;logo&quot;]/span[@class=&quot;logo-lg&quot;]</value>
      <webElementGuid>7def7f37-4a3e-4931-815c-ccd97a09b1a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/preceding::span[1]</value>
      <webElementGuid>4baf4bc7-0298-4cae-b0e7-9e5fa36d736f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>d13a0171-364b-4794-8f4c-800a9328fc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TAJALAPAK.COM' or . = 'TAJALAPAK.COM')]</value>
      <webElementGuid>c6271f36-ece3-41f4-8248-ea9a9c5ce410</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
