<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BatalHapus</name>
   <tag></tag>
   <elementGuidId>1fedba93-9305-4de1-9f61-61dd8bd5f125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu > li:nth-of-type(6) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;return confirm('Apa anda yakin Pesanan ini dibatalkan dan Hapus Data?')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4189353f-7fc3-40cd-8a77-c888883d7ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Apa anda yakin Pesanan ini dibatalkan dan Hapus Data?')</value>
      <webElementGuid>6e129b31-7bdb-4566-a8ed-23bcad64d0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=123&amp;batal=xx</value>
      <webElementGuid>0730f198-364b-46b4-8bc7-f694c9c96212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batal/Hapus</value>
      <webElementGuid>3d1fffcd-da8e-40bc-9672-d01ba7027af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/center[1]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[6]/a[1]</value>
      <webElementGuid>488282aa-8cdc-4b00-98d1-20952aeb8fc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;return confirm('Apa anda yakin Pesanan ini dibatalkan dan Hapus Data?')&quot;]</value>
      <webElementGuid>e8d5ff21-dea0-40a0-a2dc-dcc48d528399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[8]/center/div/ul/li[6]/a</value>
      <webElementGuid>c88003af-1228-4ccc-9e14-5f7eed2c5954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Batal/Hapus')]</value>
      <webElementGuid>f46f0045-a4e8-4db9-bc71-5e6a0226a4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[1]/following::a[1]</value>
      <webElementGuid>438c81c1-4de2-4625-9493-9527d7ecc1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dikirim'])[1]/following::a[2]</value>
      <webElementGuid>78b8dbd3-186c-4b94-9e17-cda9a76c56dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 1 of 1 entries (filtered from 39 total entries)'])[1]/preceding::a[4]</value>
      <webElementGuid>dce165c8-cc7b-4f32-982d-e618ab08779a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Batal/Hapus']/parent::*</value>
      <webElementGuid>c8edb561-6608-4a8d-8552-10180771382f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=123&amp;batal=xx')]</value>
      <webElementGuid>b745696a-6a24-4442-b2c8-5b4e20b42210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[6]/a</value>
      <webElementGuid>a087fade-55dc-4810-9823-b4da0894fa0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=123&amp;batal=xx' and (text() = 'Batal/Hapus' or . = 'Batal/Hapus')]</value>
      <webElementGuid>4031bbf3-5143-4df6-82f5-9d40c3277a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
