<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TUJUAN KABUPATEN</name>
   <tag></tag>
   <elementGuidId>8d190076-aed8-4841-96e1-cbcf3f46049b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list_kotakabt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='list_kotakabt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23895464-af8d-4aec-a992-ad3530dcb18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>fada9030-c4e2-48c5-823f-de8fe0e17f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kota_idt</value>
      <webElementGuid>78a061cc-3063-44ce-bd53-47a37e7a7016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list_kotakabt</value>
      <webElementGuid>b0e8ea72-7a2d-4558-90b6-20da9055420a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      - Pilih Kota / Kabupaten -
                      </value>
      <webElementGuid>94359416-c271-4f92-b055-e62650c44445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_kotakabt&quot;)</value>
      <webElementGuid>7133869f-2cb9-4787-97a8-a19c61cc574e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='list_kotakabt']</value>
      <webElementGuid>6a3a9616-0644-41ed-9d7d-0877af1cba7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan'])[1]/following::select[2]</value>
      <webElementGuid>5267839f-37a1-4e43-94a8-b203a8cb3427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posisi'])[1]/following::select[5]</value>
      <webElementGuid>c2fffbe3-d045-4d75-abd2-8a1e85359e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongkir (Rp)'])[1]/preceding::select[2]</value>
      <webElementGuid>6e019428-97e2-422f-8073-7fe52a2c5f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan'])[1]/preceding::select[2]</value>
      <webElementGuid>6a69a16b-2f4c-44f9-b835-c3bffe36d408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/select[2]</value>
      <webElementGuid>a641b084-88c7-47cd-aa55-5a679d79fb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kota_idt' and @id = 'list_kotakabt' and (text() = '
                      - Pilih Kota / Kabupaten -
                      ' or . = '
                      - Pilih Kota / Kabupaten -
                      ')]</value>
      <webElementGuid>2cb45b88-0a18-491f-afe0-2d2463c4a909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
