<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jk perempuan</name>
   <tag></tag>
   <elementGuidId>fdfa588f-e334-4529-94b9-2ed4a6cc7dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='d'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>30744a90-8d0a-473d-82c4-77fa1169119e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1695364560335</value>
      <webElementGuid>3b8637bd-ec46-4261-aa19-4ae807155d9b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
